version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - deploy/env/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file:
      - deploy/env/api.env
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:4000'

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    env_file:
      - deploy/env/web.env
    depends_on:
      - api
    ports:
      - '3000:3000'

volumes:
  postgres:
