version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file:
      - ./env/api.env
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ..
      dockerfile: Dockerfile.web
    restart: unless-stopped
    env_file:
      - ./env/web.env
    depends_on:
      - api

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - web
      - api

volumes:
  postgres:
  caddy_data:
  caddy_config:
